### PR TITLE
Sign request for AWS IAM authentication using version 4

### LINKED ISSUE #17: iam_request_headers:  invalid character 'X' looking for beginning of value
IAM Connection error
org.mule.runtime.api.connection.ConnectionException: {"errors":["error converting input X-Vault-AWS-IAM-Server-ID=dev.vault.test.com for field \"iam_request_headers\": invalid character 'X' looking for beginning of value"]}
at com.avioconsulting.mule.connector.vault.provider.internal.vault.client.auth.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:52)
    at com.avioconsulting.mule.connector.vault.provider.internal.vault.client.VaultClient.authenticate(VaultClient.java:47)
    at com.avioconsulting.mule.connector.vault.provider.internal.connection.impl.BasicVaultConnection.<init>(BasicVaultConnection.java:34)
    at com.avioconsulting.mule.connector.vault.provider.internal.connection.provider.VaultIamConnectionProvider.connect(VaultIamConnectionProvider.java:79)
    at com.avioconsulting.mule.connector.vault.provider.internal.connection.provider.VaultIamConnectionProvider.connect(VaultIamConnectionProvider.java:25)
    at org.mule.runtime.module.extension.internal.runtime.config.ClassLoaderConnectionProviderWrapper.connect(ClassLoaderConnectionProviderWrapper.java:60)
    at org.mule.runtime.core.internal.connection.ConnectionUtils.connect(ConnectionUtils.java:49)
    at org.mule.runtime.core.internal.connection.AbstractConnectionProviderWrapper.connect(AbstractConnectionProviderWrapper.java:64)
    at org.mule.runtime.core.internal.connection.ErrorTypeHandlerConnectionProviderWrapper.connect(ErrorTypeHandlerConnectionProviderWrapper.java:64)
    at org.mule.runtime.core.internal.connection.ConnectionUtils.connect(ConnectionUtils.java:49)
    at org.mule.runtime.core.internal.connection.AbstractConnectionProviderWrapper.connect(AbstractConnectionProviderWrapper.java:64)
    at org.mule.runtime.core.internal.connection.DefaultConnectionProviderWrapper.connect(DefaultConnectionProviderWrapper.java:52)
    at org.mule.runtime.core.internal.connection.CachedConnectionManagementStrategy.createConnection(CachedConnectionManagementStrategy.java:95)
    at org.mule.runtime.core.api.util.func.CheckedSupplier.get(CheckedSupplier.java:25)
    at org.mule.runtime.api.util.LazyValue.get(LazyValue.java:77)
    at org.mule.runtime.core.internal.connection.CachedConnectionManagementStrategy.getConnectionHandler(CachedConnectionManagementStrategy.java:63)
    at org.mule.runtime.core.internal.connection.DefaultConnectionManager.getConnection(DefaultConnectionManager.java:241)
    at org.mule.runtime.core.internal.connection.DefaultConnectionManager.lambda$testConnectivity$1(DefaultConnectionManager.java:160)
    at org.mule.runtime.core.internal.connection.DefaultConnectionManager.doTestConnectivity(DefaultConnectionManager.java:176)
    at org.mule.runtime.core.internal.connection.DefaultConnectionManager.testConnectivity(DefaultConnectionManager.java:152)
    at org.mule.runtime.core.internal.connection.DelegateConnectionManagerAdapter$EagerConnectionManagerAdapter.testConnectivity(DelegateConnectionManagerAdapter.java:176)
    at org.mule.runtime.core.internal.connection.DelegateConnectionManagerAdapter.testConnectivity(DelegateConnectionManagerAdapter.java:98)
    at org.mule.runtime.module.extension.api.tooling.ExtensionConnectivityTestingStrategy.testConnectivity(ExtensionConnectivityTestingStrategy.java:82)
    at org.mule.runtime.core.internal.connectivity.DefaultConnectivityTestingService.testConnection(DefaultConnectivityTestingService.java:88)
    at org.mule.runtime.config.internal.LazyConnectivityTestingService.testConnection(LazyConnectivityTestingService.java:57)
    at com.mulesoft.agent.services.tooling.MuleAgentConnectivityTestingService.testConnection(MuleAgentConnectivityTestingService.java:77)
    at com.mulesoft.agent.external.handlers.tooling.ToolingRequestHandler.lambda$applicationTestConnection$19(ToolingRequestHandler.java:482)
    at com.mulesoft.agent.util.ResponseHelper.response(ResponseHelper.java:88)
    at com.mulesoft.agent.external.handlers.tooling.ToolingRequestHandler.applicationTestConnection(ToolingRequestHandler.java:481)
    at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
    at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:876)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
    at com.mulesoft.agent.rest.RequestLoggingFilter.doFilter(RequestLoggingFilter.java:95)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
    at com.mulesoft.agent.rest.AuthorizationFilter.doFilter(AuthorizationFilter.java:49)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.Server.handle(Server.java:505)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
    at java.lang.Thread.run(Thread.java:748)

### PR DESCRIPTION
**Pull request by talyssoncastro**

### CODE REVIEW

File: src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/connection/provider/VaultIamConnectionProvider.java [hunk 1]
```diff
@@ -54,9 +54,18 @@
...
     private String iamRequestBody;
 
-    @DisplayName("IAM Request Headers")
+    @DisplayName("IAM Server ID")
     @Parameter
-    private String iamRequestHeaders;
+    @Optional
+    private String iamServerId;
+
+    @DisplayName("IAM Access Key")
```
Comment (adammead) [inline src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/connection/provider/VaultIamConnectionProvider.java]: Should this be IAM access key, or AWS access key? Same for the secret.

File: src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/vault/client/auth/AWSIAMAuthenticator.java [hunk 2]
```diff
@@ -45,10 +62,49 @@ public String getAuthPayload(VaultConfig config) throws VaultException {
             payload.addProperty("role", this.role);
         }
 
+        String encodedIamRequestHeaders = new String(Base64.getEncoder().encode(generateHeaders().getBytes(StandardCharsets.UTF_8)));
```
Comment (adammead) [inline src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/vault/client/auth/AWSIAMAuthenticator.java]: Since we have to base64 encode this for the user, we should do the same for the request body and URL so they're readable in the configuration. Since they are usually set to the same values for everyone, we should make those defaults as well.

File: src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/connection/provider/VaultIamConnectionProvider.java [hunk 3]
```diff
@@ -54,9 +54,18 @@
...
+    @Parameter
+    private String iamAccessKey;
+
+    @DisplayName("IAM Secret Key")
+    @Parameter
+    private String iamSecretKey;
```
Comment (adammead) [inline src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/connection/provider/VaultIamConnectionProvider.java]: I think there is a @Password annotation or something like that to hide the value in the UI that would be good to use on this field

File: src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/vault/client/auth/AWSIAMAuthenticator.java [hunk 4]
```diff
@@ -45,10 +62,46 @@ public String getAuthPayload(VaultConfig config) throws VaultException {
...
+        getIamServerId().ifPresent(serverId -> awsHeaders.put("x-vault-aws-iam-server-id", serverId));
+
+        AWSV4Auth awsV4Auth = new AWSV4Auth.Builder(iamAccessKey, iamSecretKey)
+                .regionName(DEFAULT_REGION)
+                .serviceName(DEFAULT_SERVICE_NAME)
+                .httpMethodName(DEFAULT_METHOD)
+                .canonicalURI(DEFAULT_CANONICAL_URI)
+                .queryParametes(null)
+                .awsHeaders(awsHeaders)
+                .payload(DEFAULT_PAYLOAD)
```
Comment (adammead) [inline src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/vault/client/auth/AWSIAMAuthenticator.java]: If the user specifies an iamRequestBody, that's what we'll need to sign. Otherwise, we can use the default value.

File: src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/vault/client/auth/AWSIAMAuthenticator.java [hunk 5]
```diff
@@ -45,10 +62,46 @@ public String getAuthPayload(VaultConfig config) throws VaultException {
...
+
+        TreeMap<String, String> awsHeaders = new TreeMap();
+        awsHeaders.put("host", DEFAULT_HOST);
+        getIamServerId().ifPresent(serverId -> awsHeaders.put("x-vault-aws-iam-server-id", serverId));
+
+        AWSV4Auth awsV4Auth = new AWSV4Auth.Builder(iamAccessKey, iamSecretKey)
+                .regionName(DEFAULT_REGION)
+                .serviceName(DEFAULT_SERVICE_NAME)
+                .httpMethodName(DEFAULT_METHOD)
+                .canonicalURI(DEFAULT_CANONICAL_URI)
```
Comment (adammead) [inline src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/vault/client/auth/AWSIAMAuthenticator.java]: We'll need to parse the iamRequestUrl to retrieve the host, canonical URI, and query parameters, since it may be different.

**Review by adammead — COMMENTED** [review]
A few little things.

File: src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/connection/provider/VaultIamConnectionProvider.java (hunk 3 above)
Comment (adammead) [reply src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/connection/provider/VaultIamConnectionProvider.java]: I just validated it is `@Password`

File: src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/vault/client/auth/AWSIAMAuthenticator.java [hunk 6]
```diff
@@ -46,9 +57,51 @@ public String getAuthPayload(VaultConfig config) throws VaultException {
...
+        headers.put("Content-Type", "application/x-www-form-urlencoded");
+        headers.put("X-Amz-Date", awsV4Auth.getxAmzDate());
+        getIamServerId().ifPresent(serverId -> headers.put("x-vault-aws-iam-server-id", serverId));
+        Gson gson = new Gson();
+        String textOfHeaders = gson.toJson(headers);
+
+        return textOfHeaders;
+    }
+
+    private String encondeBase64(String value) {
```
Comment (adammead) [inline src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/vault/client/auth/AWSIAMAuthenticator.java]: Rename this to `encodeBase64` looks like a typo

File: src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/vault/client/auth/algorithm/AWSV4SignProperties.java [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+    }
+
+    private void process(String url) {
+        URI uri;
+        try {
+            uri = new URI(url);
+            host = uri.getHost();
+            canonicalUri = uri.getPath();
+            queryParameters = splitQuery(uri.getQuery());
+        } catch (URISyntaxException e) {
```
Comment (adammead) [inline src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/vault/client/auth/algorithm/AWSV4SignProperties.java:66]: I think we want to at least log that this is happening so we can understand why the defaults are being used when the user is entering an URL. Otherwise we should throw the exception so the URL can be fixed.

File: src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/vault/client/auth/algorithm/AWSV4SignProperties.java [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+    private AbstractMap.SimpleImmutableEntry<String, String> splitQueryParameter(String it) {
+        final int idx = it.indexOf("=");
+        final String key = idx > 0 ? it.substring(0, idx) : it;
+        final String value = idx > 0 && it.length() > idx + 1 ? it.substring(idx + 1) : null;
+        try {
+            return new AbstractMap.SimpleImmutableEntry<>(
+                    URLDecoder.decode(key, "UTF-8"),
+                    URLDecoder.decode(value, "UTF-8")
+            );
+        } catch (UnsupportedEncodingException e) {
```
Comment (adammead) [inline src/main/java/com/avioconsulting/mule/connector/vault/provider/internal/vault/client/auth/algorithm/AWSV4SignProperties.java:97]: This should be logged too

**Review by adammead — APPROVED** [review]
